# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Utils' do
use_frameworks!
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
### For Email Link/Passwordless Auth
pod 'FirebaseDynamicLinks'
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
               end
          end
   end
end
